---
- name: Installing packages for Python
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: Create directory for HTTP server
  file:
    path: /home/ubuntu/basic-http-server
    state: directory

- name: Install Apache2
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes
